"""update

Revision ID: 485dbcb27a68
Revises: f9db50c458db
Create Date: 2024-01-11 14:16:01.206353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485dbcb27a68'
down_revision = 'f9db50c458db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_customer',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'customer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_customer')
    # ### end Alembic commands ###
