"""added database

Revision ID: 4c304c844638
Revises: eeefcfe40bc8
Create Date: 2024-01-09 23:52:08.084353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c304c844638'
down_revision = 'eeefcfe40bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
