"""database

Revision ID: 4d84d5211799
Revises: c60c8179915f
Create Date: 2024-01-09 23:44:14.500953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d84d5211799'
down_revision = 'c60c8179915f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
