"""database

Revision ID: 5ba7d8200f63
Revises: 4c304c844638
Create Date: 2024-01-09 23:56:46.593169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba7d8200f63'
down_revision = '4c304c844638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'location')
    # ### end Alembic commands ###
