"""date

Revision ID: 9b3669e6210f
Revises: 485dbcb27a68
Create Date: 2024-01-12 00:10:38.795247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3669e6210f'
down_revision = '485dbcb27a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('created_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'created_at')
    # ### end Alembic commands ###
